name: ${project.name}
version: ${project.version}
main: tr.com.infumia.plugin.InfumiaPlugin
commands:
  infumia:
    usage: /infumia [reload|update]
    permission: infumiaplugin.command.main
    description: Main command of Infumia Plugin.
