name: publish

on:
  pull_request:
    types: [ closed ]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label

      - if: ${{ steps.release-label.outputs.level == null }}
        run: exit 1

      - uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: version
        with:
          owner: Infumia
          repo: InfumiaLib

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.version.outputs.release }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          [[ "${{ steps.bump-semver.outputs.new_version }}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
          mvn versions:set -DnewVersion="${{ steps.bump-semver.outputs.new_version }}"
          mvn package -T 2

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: '${{ steps.bump-semver.outputs.new_version }}'
          name: '${{ steps.bump-semver.outputs.new_version }}'
          body: '[Changelog](https://github.com/Infumia/InfumiaLib/compare/${{ steps.version.outputs.release }}...${{ steps.bump-semver.outputs.new_version }})'
          files: |
            paper/target/InfumiaPaper.jar
            velocity/target/InfumiaVelocity.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: badasintended/autojitpack@v0
